# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll
title: Developer Name

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Project Title

description: Stylish Jekyll Theme
githubData:
  show: true
  forks: false
  stared: true
repositoryName: dan-seminar-subscriber
author:
  name: dan
  email: mahathun.online@gmail.com
  github: mahathun
  twitter: mahathun
  # pinterest: asd123
  linkedin: dan-mahavithana-50212b68
  bitbucket: mahathun
  facebook: mahathun
  bio: ~ A good programmer looks both ways before crossing an one-way street. ~
  email_md5:
  url: http://www.danmahavithana.com


categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:
